import type { ConceptSource } from "../types";

const category = "Cash flow" as const;

export const cashFlow: ConceptSource[] = [
  {
    slug: "operating-cash-flow",
    term: "Operating cash flow",
    aliases: ["cash from operations", "OCF"],
    category,
    level: "intermediate",
    requires: ["net-income"],
    metrics: ["operating_cash_flow"],
    oneLiner: "Cash actually generated by running the business, as opposed to accounting profit.",
    body: `[Net income](/learn/net-income) is an accounting construct. Revenue is booked when earned rather than when paid, and non-cash charges like depreciation reduce it without any money leaving. Operating cash flow strips those effects out and reports what actually moved.

The gap between the two is one of the most informative things on a company's statements. Profit consistently well above operating cash flow means earnings are being recognised faster than customers pay — sometimes a growing business extending credit, sometimes the early stage of an accounting problem.

Cash is much harder to fake than profit. When the two disagree, the cash flow statement is where to start.`,
  },
  {
    slug: "capex",
    term: "Capital expenditure",
    aliases: ["capex"],
    category,
    level: "intermediate",
    metrics: ["capex"],
    oneLiner: "Money spent on long-lived assets — factories, equipment, data centres.",
    body: `Capex is spending on things that will produce value for years. It does not hit the income statement immediately; instead the cost is spread across the asset's useful life as depreciation.

That treatment is why capex is invisible in profit but very visible in cash. A company can report healthy earnings while pouring every available dollar into new facilities.

Distinguishing **maintenance** capex, which merely keeps existing operations running, from **growth** capex, which adds capacity, is one of the more useful analytical exercises. Companies rarely split it out, but the difference between the two is the difference between a treadmill and an investment.`,
  },
  {
    slug: "free-cash-flow",
    term: "Free cash flow",
    aliases: ["FCF"],
    category,
    level: "intermediate",
    requires: ["operating-cash-flow", "capex"],
    metrics: ["free_cash_flow"],
    oneLiner:
      "Operating cash flow minus capital expenditure — cash genuinely available to owners.",
    body: `    free cash flow = operating cash flow − capital expenditure

This is the cash left after the business has paid for everything needed to keep operating. It is what can fund [dividends](/learn/dividend), [buybacks](/learn/buyback), debt repayment or acquisitions without raising new money.

Many people consider it the single most honest number a company publishes. It is far harder to manipulate than [net income](/learn/net-income), because it reflects money that actually moved.

The caveat is that it is lumpy. A company building a large facility will show poor or negative free cash flow for a few years without anything being wrong. Read it over a multi-year window, not a quarter.`,
  },
  {
    slug: "buyback",
    term: "Share buyback",
    aliases: ["repurchase", "share repurchase"],
    category,
    level: "intermediate",
    requires: ["shares-outstanding"],
    oneLiner:
      "A company buying its own shares, which reduces the share count and lifts per-share figures.",
    body: `When a company repurchases its own stock, those shares are retired. [Shares outstanding](/learn/shares-outstanding) falls, so each remaining share represents a larger slice of the business — and [EPS](/learn/eps) rises even if profit is flat.

Buybacks are a way of returning cash to shareholders, an alternative to [dividends](/learn/dividend), and more tax-efficient in many jurisdictions since nothing is paid out to be taxed.

Whether one creates value depends entirely on price. Buying back undervalued stock benefits the remaining holders; buying back overvalued stock destroys value, and companies have a well-documented habit of repurchasing most aggressively at market peaks.

Also watch for buybacks that merely offset shares issued to employees. The share count is the honest test: if it is not falling, cash is going out with nothing to show for it.`,
  },
];
